#Home
  bannerText: 'somos a Youse'
  myAccountText: 'MINHA CONTA'

#LoginPage
  loginText: 'Faça seu login para acessar sua conta Youse.'

#RegisterPage
  registerText: 'Cadastre-se para ser um Youse'

 #AccountPage 
  registerSucess: 'Bem vindo! Você realizou seu registro com sucesso.'
  loginSucess: 'Login efetuado com sucesso.'
