#Home
  bannerText: 'somos a Youse'
  myAccountText: 'MINHA CONTA'

#LoginPage
  loginText: 'Faça seu login para acessar sua conta Youse.'

#RegisterPage
  registerText: 'Cadastre-se para ser um Youse'

 #AccountPage 
  registerSucess: 'Bem vindo! Você realizou seu registro com sucesso.'
  loginSucess: 'Login efetuado com sucesso.'

#Quotation data
  nome: 'Bruno Nascimento'
  pra mim: 'true'
  para outra pessoa: 'false'
  telefone: '11999999999'
  email: 'testeyu@testeyu.com'
  marca: 'FORD'
  modelo: "FIESTA"
  anoModelo: '2013'
  versao: 'FIESTA 1.6 16V FLEX MEC. 5P (Gasolina / Flex)'
  particular: 'auto|private'
  possuiCarro: 'já tenho'
  já estou utilizando: 'true'
  já tenho: 'true'
  sou: 'true'
  cep: '05734140'
  seguradoOpcao: 'sou'
  dataNascimento: '19011989'
  tive há 2 anos: '2'
  masculino: 'male'

  #PagesQuatation
  sobrevoce: 'Oi, a gente quer conhecer você melhor, é rapidinho'
  veiculo: 'Agora, fale um pouquinho sobre o seu carro.'
  sugestoes: 'Essa é a parte mais legal: 
bora deixar o seguro com a sua cara?'
  assistencia: 'Sugestões de Assistências Youse para vc. 
Conheça as assistências e serviços disponíveis pra você e deixe o seguro do seu jeito.'
  pagamento: 'Aeee! Estamos quase lá. 
Conta aí um pouquinho mais sobre vc.'
  