source 'http://rubygems.org'

gem 'cucumber'
gem 'rspec'
gem 'rake'
gem 'capybara'
gem 'selenium-webdriver'
gem 'site_prism'
gem 'chromedriver-helper'
gem 'pry'
gem 'testgen'
gem 'faker'
gem 'fabrication'